apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-test-node-app-deployment
  labels:
    app: k3s-test-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-test-node-app
  template:
    metadata:
      labels:
        app: k3s-test-node-app
    spec:
      containers:
      - name: k3s-test-node-app
        image: [YOUR_DOCKER_IMAGE]:1.0.0
        env:
        - name: APP_VERSION
          value: "1.0.0"
        ports:
        - containerPort: 3000
